print("ESTOY CAMBIANDO EL ARCHIVO EN SU TOTALIDAD !")
print("ESTOY LLEVANDO CURSOS DE UDEMY PARA APRENDER BIEN GIT OK")
print("ESTOY LLEVANDO CURSOS DE UDEMY PARA APRENDER GIT!")

print("agregare esta nueva linea")

print("AGREGUE OTRA NUEVA LINEA PARA PODER HACER PRACTICAS")